version: 0.0
os: linux
files:
  - source: build/libs/
    destination: /home/ec2-user/app/studymaker/
  - source: scripts/start.sh
    destination: /home/ec2-user/app/studymaker/
  file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user
