version: 0.0
os: linux
files:
  - source: /**/*.jar
    destination: /home/ec2-user/app/studymaker/
  - source: /**/start.sh
    destination: /home/ec2-user/app/studymaker/
hooks:
  AfterInstall:
    - location: start.sh
      timeout: 180
      runas: ec2-user
