spring:
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  secret: zf5sG7YPj2UYnig77n5IrtZ0nWR71LKTjlS0mNfztCAfVvuOHEvgRNi2qmMpI1oMnSvRxTYVbtV8lgShU1RA
  token-validity-in-millisecond: 18000