logging.level.org.hibernate.SQL: debug            # 로그 형식으로 쿼리 보여주기
spring.jpa.properties.hibernate.format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧
spring.jpa.hibernate.ddl-auto: create             # 서버 시작에 테이블 생성

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studymaker
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  secret: studymaker_is_good_web_application_for_developer
  issuer: studymaker
  tokenValidityTimeLimit: 600000
